defmodule Kogen.State.Event do
  @moduledoc "A decoded run-journal event used by Kernel reports."

  @enforce_keys [:event]
  defstruct [
    :event,
    :recipe,
    :roles,
    :phase,
    :name,
    :stage,
    :class,
    :reason,
    :detail,
    :path,
    :declared_domains,
    :test_ids,
    :seed,
    :status,
    :result,
    :approval_commit,
    :approved_by,
    :base_sha,
    :ledger,
    :receipts,
    :candidate_diff,
    :excluded_paths,
    :red_checks,
    :acceptance_items,
    :model,
    :effort,
    :attempt,
    :trigger,
    :summary,
    :findings,
    :gate_summary,
    :stop,
    :escalation,
    :started_at,
    :finished_at,
    :credential_source,
    :credential_label,
    :tokens,
    :wall_ms,
    :setup_key,
    :saved_wall_ms,
    :commit,
    :metrics,
    :branch,
    :item,
    :verdict,
    :rung,
    :outcomes,
    :attempts,
    :failing,
    :experimental,
    :partial
  ]

  @type t :: %__MODULE__{
          event: String.t(),
          recipe: String.t() | nil,
          roles: map() | nil,
          phase: String.t() | nil,
          name: String.t() | nil,
          stage: String.t() | nil,
          class: String.t() | nil,
          reason: String.t() | nil,
          detail: String.t() | nil,
          path: String.t() | nil,
          declared_domains: [String.t()] | nil,
          test_ids: [String.t()] | nil,
          seed: non_neg_integer() | nil,
          status: term(),
          result: term(),
          approval_commit: String.t() | nil,
          approved_by: String.t() | nil,
          base_sha: String.t() | nil,
          ledger: term(),
          receipts: term(),
          candidate_diff: String.t() | nil,
          excluded_paths: [String.t()] | nil,
          red_checks: [map()] | nil,
          acceptance_items: [map()] | nil,
          model: String.t() | nil,
          effort: String.t() | nil,
          attempt: String.t() | nil,
          trigger: String.t() | nil,
          summary: String.t() | nil,
          findings: [String.t()] | nil,
          gate_summary: map() | nil,
          stop: map() | nil,
          escalation: map() | nil,
          started_at: integer() | nil,
          finished_at: integer() | nil,
          credential_source: String.t() | nil,
          credential_label: String.t() | nil,
          tokens: term(),
          wall_ms: non_neg_integer() | nil,
          setup_key: String.t() | nil,
          saved_wall_ms: non_neg_integer() | nil,
          commit: String.t() | nil,
          metrics: map() | nil,
          branch: String.t() | nil,
          item: String.t() | nil,
          verdict: String.t() | nil,
          rung: String.t() | nil,
          outcomes: [map()] | nil,
          attempts: [String.t()] | nil,
          failing: map() | nil,
          experimental: boolean() | nil,
          partial: boolean() | nil
        }
end
